# Generated by Django 5.0.7 on 2024-07-22 16:11

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_file_uploading_to, verbose_name='photo')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_file_uploading_to, verbose_name='image of header')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'Profile',
            },
        ),
    ]
