# Generated by Django 5.0.7 on 2024-08-19 12:06

import django.db.models.deletion
import server.utils.functions.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('task_count', models.IntegerField(editable=False, verbose_name='количесвто задач')),
                ('completed_task_count', models.IntegerField(editable=False, verbose_name='количество выполненных задач')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=server.utils.functions.files.project_image_uploading_to, verbose_name='иконка')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=server.utils.functions.files.project_image_uploading_to, verbose_name='фоновая картинка')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('members', models.ManyToManyField(db_table='ProjectMembers', related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_projects', to=settings.AUTH_USER_MODEL, verbose_name='основатель')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Задача проекта',
                'verbose_name_plural': 'Задачи проектов',
                'db_table': 'ProjectTask',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='дата')),
                ('text', models.TextField(verbose_name='текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('likes', models.ManyToManyField(db_table='LikedBy', related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='лайки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projecttask', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.utils.functions.files.project_task_file_uploading_to, verbose_name='файл')),
                ('load_date', models.DateField(auto_now_add=True, verbose_name='дата загрузки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projecttask', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'Файл задачи проекта',
                'verbose_name_plural': 'Файлы задач проектов',
                'db_table': 'ProjectTaskFile',
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('color', models.CharField(max_length=6, verbose_name='цвет')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Приоритет задачи проекта',
                'verbose_name_plural': 'Приоритеты задач проектов',
                'db_table': 'ProjectTaskPriority',
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projecttaskpriority', verbose_name='приоритет'),
        ),
        migrations.CreateModel(
            name='ProjectTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('color', models.CharField(max_length=6, verbose_name='цвет')),
                ('is_means_completeness', models.BooleanField(verbose_name='означает ли законченность')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projects.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'Статус задачи проекта',
                'verbose_name_plural': 'Статусы задач проектов',
                'db_table': 'ProjectTaskStatus',
            },
        ),
        migrations.AddField(
            model_name='projecttask',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projecttaskstatus', verbose_name='статус'),
        ),
    ]
