# Generated by Django 5.0.7 on 2024-08-21 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_completed_task_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttaskfile',
            name='load_date',
        ),
        migrations.AddField(
            model_name='projecttaskfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата загрузки'),
            preserve_default=False,
        ),
    ]
