# Generated by Django 5.0.7 on 2025-04-08 18:30

import django.db.models.deletion
import server.utils.functions.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='временная метка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_messages', to='projects.project', verbose_name='проект')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_messages', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение проекта',
                'verbose_name_plural': 'Сообщения проектов',
                'db_table': 'ProjectMessage',
            },
        ),
        migrations.CreateModel(
            name='ProjectMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.utils.functions.files.project_message_file_uploading_to, verbose_name='файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.projectmessage', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Файл сообщения проекта',
                'verbose_name_plural': 'Файлы сообщений проектов',
                'db_table': 'ProjectMessageFile',
            },
        ),
    ]
