# Generated by Django 5.0.7 on 2025-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projecttaskfile_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessagefile',
            name='file_name',
            field=models.CharField(default='', editable=False, max_length=128, verbose_name='название файла'),
            preserve_default=False,
        ),
    ]
