# Generated by Django 5.0.7 on 2024-07-25 14:57

import auth_sys.validators
import django.db.models.deletion
import server.utils.functions.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128, validators=[auth_sys.validators.validate_password], verbose_name='пароль')),
                ('first_name', models.CharField(max_length=128, verbose_name='имя')),
                ('last_name', models.CharField(max_length=128, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=128, null=True, verbose_name='отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=server.utils.functions.files.user_file_uploading_to, verbose_name='фото')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to=server.utils.functions.files.user_file_uploading_to, verbose_name='фоновая картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'User',
                'indexes': [models.Index(fields=['email'], name='email_index'), models.Index(fields=['first_name', 'last_name', 'patronymic'], name='full_name_index')],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'Token',
                'abstract': False,
            },
        ),
    ]
