# Generated by Django 5.0.7 on 2024-09-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='may_be_invited',
            field=models.BooleanField(default=True, verbose_name='может быть приглашен'),
        ),
    ]
