# Generated by Django 5.0.7 on 2024-07-23 10:12

import auth_sys.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[auth_sys.validators.validate_password], verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='отчество'),
        ),
    ]
