# Generated by Django 5.0.7 on 2024-08-01 10:10

import django.db.models.deletion
import server.utils.functions.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Пользовательская задача',
                'verbose_name_plural': 'Пользовательские задачи',
                'db_table': 'UserTask',
            },
        ),
        migrations.CreateModel(
            name='UserTaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.utils.functions.files.user_task_file_uploading_to, verbose_name='файл')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='user_tasks.usertask', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'Файл пользовательской задачи',
                'verbose_name_plural': 'Файлы пользовательских задач',
                'db_table': 'UserTaskFile',
            },
        ),
        migrations.CreateModel(
            name='UserTaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='users_task_list/', verbose_name='фоновая картинка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_list', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Пользовательский список задач',
                'verbose_name_plural': 'Пользовательские списки задач',
                'db_table': 'UserTaskList',
            },
        ),
        migrations.AddField(
            model_name='usertask',
            name='task_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_tasks.usertasklist', verbose_name='список задач'),
        ),
        migrations.CreateModel(
            name='UserTaskListPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('color', models.CharField(max_length=6, verbose_name='цвет')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='user_tasks.usertasklist', verbose_name='список задач')),
            ],
            options={
                'verbose_name': 'Приоритет пользовательского списка задач',
                'verbose_name_plural': 'Приоритеты пользовательских списков задач',
                'db_table': 'UserTaskListPriority',
            },
        ),
        migrations.AddField(
            model_name='usertask',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='user_tasks.usertasklistpriority', verbose_name='приоритет'),
        ),
        migrations.CreateModel(
            name='UserTaskListStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('color', models.CharField(max_length=6, verbose_name='цвет')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='user_tasks.usertasklist', verbose_name='список задач')),
            ],
            options={
                'verbose_name': 'Статус пользовательского списка задач',
                'verbose_name_plural': 'Статусы пользовательских списков задач',
                'db_table': 'UserTaskListStatus',
            },
        ),
        migrations.AddField(
            model_name='usertask',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='user_tasks.usertaskliststatus', verbose_name='статус'),
        ),
    ]
