# Generated by Django 5.0.7 on 2024-08-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата загрузки'),
        ),
    ]
