# Generated by Django 5.0.7 on 2024-07-26 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('INV_GROUP', 'Приглашение в группу'), ('JOINED_GROUP', 'Пополнение в группе'), ('EXC_GROUP', 'Исключен из группы'), ('LEAVE_GROUP', 'Убавление в группе')], editable=False, max_length=56, verbose_name='тема')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('text', models.TextField(editable=False, verbose_name='текст')),
                ('is_readed', models.BooleanField(default=False, editable=False, verbose_name='прочитано ли')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
                ('sender_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.group', verbose_name='группа-отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'Message',
            },
        ),
    ]
