# Generated by Django 5.0.7 on 2024-08-20 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0001_initial'),
        ('projects', '0002_alter_project_completed_task_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.project', verbose_name='проект-отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(choices=[('INV_GROUP', 'Приглашение в группу'), ('JOINED_GROUP', 'Пополнение в группе'), ('EXC_GROUP', 'Исключен из группы'), ('LEAVE_GROUP', 'Убавление в группе'), ('INV_PROJECT', 'Приглашение в проект'), ('JOINED_PROJECT', 'Пополнение в проекте'), ('EXC_PROJECT', 'Исключен из проекта')], editable=False, max_length=56, verbose_name='тема'),
        ),
    ]
