# Generated by Django 5.0.7 on 2024-10-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0002_message_sender_project_alter_message_topic'),
        ('projects', '0004_remove_projecttaskfile_load_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_project_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.projecttask', verbose_name='проектная-задача-отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(choices=[('INV_GROUP', 'Приглашение в группу'), ('JOINED_GROUP', 'Пополнение в группе'), ('EXC_GROUP', 'Исключен из группы'), ('LEAVE_GROUP', 'Убавление в группе'), ('INV_PROJECT', 'Приглашение в проект'), ('JOINED_PROJECT', 'Пополнение в проекте'), ('EXC_PROJECT', 'Исключен из проекта'), ('TASKS', 'Уведомление о задаче')], editable=False, max_length=56, verbose_name='тема'),
        ),
    ]
