# Generated by Django 5.0.7 on 2024-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0004_message_days_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='days_left',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='остаточные дни'),
        ),
    ]
