# Generated by Django 5.0.7 on 2025-04-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0008_alter_message_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='идентификатор сообщения'),
        ),
        migrations.AddField(
            model_name='message',
            name='messanger_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='идентификатор мессенджера'),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(choices=[('INV_GROUP', 'Приглашение в группу'), ('JOINED_GROUP', 'Пополнение в группе'), ('EXC_GROUP', 'Исключен из группы'), ('LEAVE_GROUP', 'Убавление в группе'), ('EXC_PROJECT', 'Исключение из проекта'), ('LEAVE_PROJECT', 'Убавление в проекте'), ('EXC_GROUP_MESSANGER', 'Исключен из мессенджера группы'), ('LEAVE_GROUP_MESSANGER', 'Убавление в месенджере группы'), ('GROUP_MESSAGE', 'Упоминание в мессенджере группы'), ('PROJECT_MESSAGE', 'Упоминание в мессенджере проекта'), ('TASKS', 'Уведомление о задаче')], editable=False, max_length=56, verbose_name='тема'),
        ),
    ]
