# Generated by Django 5.0.7 on 2025-03-31 17:51

import server.utils.functions.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.utils.functions.files.group_image_uploading_to, verbose_name='иконка'),
        ),
    ]
