# Generated by Django 5.0.7 on 2025-03-31 18:57

import django.db.models.deletion
import server.utils.functions.files
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=server.utils.functions.files.group_messanger_image_uploading_to, verbose_name='иконка')),
                ('name', models.CharField(max_length=128, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('members_count', models.IntegerField(default=0, editable=False, verbose_name='количество участников')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messangers', to='groups.group', verbose_name='группа')),
                ('members', models.ManyToManyField(db_table='GroupMessangerMembers', related_name='groups_messangers', to=settings.AUTH_USER_MODEL, verbose_name='участники')),
            ],
            options={
                'verbose_name': 'Мессенджер группы',
                'verbose_name_plural': 'Мессенджеры группы',
                'db_table': 'GroupMessanger',
            },
        ),
        migrations.CreateModel(
            name='GroupMessangerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='временная метка')),
                ('messanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.groupmessanger', verbose_name='мессенджер')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_messangers_messages', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение мессенджера группы',
                'verbose_name_plural': 'Сообщения мессенджера группы',
                'db_table': 'GroupMessangerMessage',
            },
        ),
        migrations.CreateModel(
            name='GroupMessangerMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=server.utils.functions.files.group_messanger_message_file_uploading_to, verbose_name='файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='groups.groupmessangermessage', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Файл сообщения мессенджера группы',
                'verbose_name_plural': 'Файлы сообщения мессенджера группы',
                'db_table': 'GroupMessangerMessageFile',
            },
        ),
    ]
