# Generated by Django 5.0.7 on 2025-04-02 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_groupmessangermessage_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessangermessage',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups_messangers_messages', to=settings.AUTH_USER_MODEL, verbose_name='отправитель'),
            preserve_default=False,
        ),
    ]
