# Generated by Django 5.0.7 on 2025-06-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_groupmessangermessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessangermessage',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='сообщение'),
        ),
    ]
